version: '3.8'

services:
  tortuosity-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount model files (if they exist)
      - ./final_model (11).pth:/app/final_model (11).pth:ro
      - ./final_model_tarsus_improved.pth:/app/final_model_tarsus_improved.pth:ro
      # Mount test image (if it exists)
      - ./meibomio.jpg:/app/meibomio.jpg:ro
      # Mount results directory for persistence
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tortuosity-api
    restart: unless-stopped
    profiles:
      - production 